# services:
  # cart-api:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:5000           # ← changed here too
  #     - DOTNET_USE_POLLING_FILE_WATCHER=true
  #   ports:
  #     - "5000:5000"     # ← NEW PUBLIC PORT
  #     - "52996:52996"   # debugger